#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect requirements (Install nginx on your web-01 - Nginx should be listening on port 80)
sudo apt-get update
sudo apt-get install -y nginx
# configureing Firewall (UFW) to allow HTTP traffic -port 80
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
