#!/usr/bin/env bash
# a Bash script containing commands to configure my Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo chmod 644 /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;\
       location = /404.html {\
           internal;\
       };' /etc/nginx/sites-available/default
sudo service nginx restart
