#!/usr/bin/env bash
# a Bash script containing commands to configure my Nginx server
# to be same as web-01 and to add a custom header file
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/hagarSamy permanent;' /etc/nginx/sites-available/default
sudo sed -i "/redirect_me/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $(hostname);' /etc/nginx/sites-available/default
sudo service nginx reload
