#!/usr/bin/env bash
# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

mysqldump -u root --all-databases -p"$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
