#!/usr/bin/env bash
# Fixing Ubuntu container’s Nginx to listen on port 80
rm /etc/nginx/sites-enabled/default
# Enable the default site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo systemctl restart nginx
