#!/usr/bin/env bash
#displaying a statement terminating it with with kill

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Send a SIGKILL signal to the process
kill -9 "$pid"
