#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format

list=$(ls)
for file in $list
do
    # cuts from delimeter "-" and extraxts 2nd part
    #(hyphen part is 1st and filename is 2nd)
	echo "$file" | cut -d "-" -f 2

done
