#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

echo "127.0.0.2		localhost" > ~/hostsEditted
# >> to append and avoid overwrite
echo "8.8.8.8		facebook.com" >> ~/hostsEditted

cp ~/hostsEditted /etc/hosts
