#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# set user to nginx
sed -i "1 i\user nginx;" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
# Replacement of all port 80 by 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# Stop any process that is currently running on 8080
# kill "$(lsof -i:8080 -t)"
# Restart nginx
su nginx -c 'service nginx restart'
