#!/usr/bin/env bash
# nginx must be running as nginx user
#sed -i "1 i\user nginx"$'\x3B' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
