#!/usr/bin/env bash
# Bash script that uses ssh to connect to my server using the private key ~/.ssh/school with the user ubuntu
# user's name@server's address
ssh -i ~/.ssh/school ubuntu@100.26.217.5
